replicaCount: 2

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  type: ClusterIP
  port: 80
  flaskPort: 5052
  mongoExpressPort: 8081

image:
  repository: shashkist/flask-contacts-app
  tag: latest
  pullPolicy: IfNotPresent

database:
  type: MONGO # Change to MYSQL for MySQL
  mongo:
    host: mongo
    port: 27017
    databaseName: flaskDB
  mysql:
    host: mysql
    port: 3306
    databaseName: flaskDB
    user: root
    password: password

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
