{{ if eq .Values.database.type "MONGO" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-express
  template: #pod defintion
    metadata:
      labels:
        app: mongo-express
    spec: # container specs
      containers:
        - name: mongo-express
          image: mongo-express:1.0.2-20-alpine3.19
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: flask-configmap
                key: MONGO_HOST
         
       

---
apiVersion: v1
kind: Service
metadata:
 name: mongo-express-service
spec:
 selector:
   app: mongo-express
 type: LoadBalancer # external service which can be accessed from outside the cluster
 ports:
   - protocol: TCP
     port: {{ .Values.service.mongoExpressPort }}
     targetPort: 8081   

{{ end }}